### ISSUE TITLE
有结合three.js 展示风的示例吗

### ISSUE THREAD

**Issue by Ants-double** [ecojust/cesium-three-vue#1]
大神，求three.js 展示风的示例

**Comment by ecojust** [comment]
风?官方好像有个风吹动衣服的demo,https://threejs.org/examples/#webgl_animation_cloth

**Comment by Ants-double** [comment]
ok，我想要这样的效果https://earth.nullschool.net/  我在这个网站上找到了一个https://github.com/cambecc/earth ，但这个不是Cesium引擎

**Comment by ecojust** [comment]
感觉可以用shader写一个纹理,然后贴在three的球体模型上,这个shader的效果当然就是类似卫星云图的,如果是cesium的话,我刚才找了一下卫星云图,但是是静态贴图实现的,所以感觉还是要写shader,cesium上自定义shader可以参考如下代码:
        var appearance = new Cesium.EllipsoidSurfaceAppearance({
            material : new Cesium.Material({
                fabric : {
                    type : 'Water',
                    uniforms : {
                        //baseWaterColor:new Cesium.Color(0.0, 0.0, 1.0, 0.5),
                        //blendColor: new Cesium.Color(0.0, 0.0, 1.0, 0.5),
                        //specularMap: 'gray.jpg',
                        normalMap: '/texture/waterNormals.jpg',
                        frequency: 1000.0,
                        animationSpeed: 0.01,
                        amplitude: 10.0
                    }
                }
            }),
            // vertexShaderSource:'',
            //重写fs，修改水面的透明度
            fragmentShaderSource:`
                varying vec3 v_positionMC;
                varying vec3 v_positionEC;
                varying vec2 v_st;
                void main(){
                    czm_materialInput materialInput;
                    vec3 normalEC = normalize(czm_normal3D * czm_geodeticSurfaceNormal(v_positionMC, vec3(0.0), vec3(1.0)));
                    
                    #ifdef FACE_FORWARD
                        normalEC = faceforward(normalEC, vec3(0.0, 0.0, 1.0), -normalEC);
                    #endif
                    
                    materialInput.s = v_st.s;
                    materialInput.st = v_st;
                    materialInput.str = vec3(v_st, 0.0);
                    materialInput.normalEC = normalEC;
                    materialInput.tangentToEyeMatrix = czm_eastNorthUpToEyeCoordinates(v_positionMC, materialInput.normalEC);
                    vec3 positionToEyeEC = -v_positionEC;
                    materialInput.positionToEyeEC = positionToEyeEC;
                    czm_material material = czm_getMaterial(materialInput);
                    
                    #ifdef FLAT
                        gl_FragColor = vec4(material.diffuse + material.emission, material.alpha);
                    #else
                        gl_FragColor = czm_phong(normalize(positionToEyeEC), material);
                        gl_FragColor.a=0.5;
                    #endif
                }
            `
        })

        var water = scene.primitives.add(new Cesium.Primitive({
            geometryInstances : instance2,
            appearance : appearance
        }));
        viewer.trackedEntity = water; // 镜头追踪，将镜头固定在对象上

**Comment by ecojust** [comment]
@Ants-double  我找到一个博客,可以借鉴一下:https://www.cnblogs.com/arxive/p/7445973.html

**Comment by ecojust** [comment]
![image](https://user-images.githubusercontent.com/30574854/66747461-2f35ed80-eeb7-11e9-818e-347a559161e0.png)

可以在fs里面多个sampler2D取样叠加,就像这样,这是我用世界地图(img)和heatmap生成的纹理叠加获得的

**Comment by ecojust** [comment]
![image](https://user-images.githubusercontent.com/30574854/66747735-d2870280-eeb7-11e9-8555-bfcb80328e94.png)

可以在fs里面多个sampler2D取样叠加,就像这样,这是我用世界地图(img)和heatmap生成的纹理叠加获得的,所以可以将 http://hint.fm/wind/gallery/oct-30.js.html 这个上面的wind map作为纹理传给fs进行叠加处理,应该就能达到你要的效果

**Comment by Ants-double** [comment]
嗯嗯，谢谢，我理解一下，webgl入门小白
